### ISSUE TITLE
Validator not accepting multiple activities

### ISSUE THREAD

**Issue by natalieesk** [w3c-social/activitystreams-validator#18]
I wanted to use the url field to validate a list of activities and I got this message:
error	/	Top-level is an array; must be an object

Is there another format it's meant to be in?

**Comment by natalieesk** [comment]
It was in this format: [{**activity**},{**activity**}]

The activities by themselves work fine.

**Comment by evanp** [comment]
So, I think the base of an Activity Streams 2.0 document has to be an Object.

https://www.w3.org/TR/activitystreams-core/#syntaxconventions

'An Activity Streams Document is a JSON document whose root value is an Activity Streams Object of any type and whose MIME media type is "application/activity+json".'

The way to do an array would be to make a collection:

https://www.w3.org/TR/activitystreams-core/#collections

I can see two ways of fixing this:

1. Add a note to this effect to the validator when the top-level content is an array.
2. Accept arrays at the top level. I think this is less good -- validators are supposed to be strict!

**Comment by evanp** [comment]
I'm going to close this; I think this works correctly.
