### ISSUE TITLE
Empty Object is Valid?

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitystreams-validator#5]
https://as2.rocks/validate?url=https%3A%2F%2Frawgit.com%2Fgobengo%2Fe786a04a723858df49d9%2Fraw%2F3119cd8e81183126a8b969b737ecf7e74f3b87e9%2Fgistfile1.txt

Is this a bug or a feature? A cursory skim of the core spec doesn't show any MUSTs that an empty object is failing to comply with.

@evanp @jasnell thoughts?

**Comment by akuckartz** [comment]
That is a great test case :smile:

**Comment by jasnell** [comment]
Yep, it's valid. Completely useless, but valid :-)

**Comment by akuckartz** [comment]
What about the completely empty string "" : valid or not ?

**Comment by jasnell** [comment]
@akuckartz .. as in `{"":""}` ? that would also be valid, albeit even more useless ;-) ... it would essentially be interpreted as a unknown extension.

**Comment by gobengo** [comment]
@akuckartz however if you mean the String `""` (no quotes), then I believe that would be invalid AS2 because it's invalid JSON.

**Comment by gobengo** [comment]
Closing since @jasnell answered my question. Empty object is valid AS2.

That's weird, but it means there's no issue with the validator right now. Maybe the spec itself, but not the validator.

I do think it would be reasonable for an AS2-consuming service to reject empty objects, and wonder if that has impliciations for conformance validators.

@jasnell Is it silly to have the spec require at least one key in the JSON Object to be a valid *AS2 Object*?

**Comment by jasnell** [comment]
AS2 purposefully takes an everything is optional approach for the base format. It is not unreasonable for an implementation to require a minimal set of metadata, however.

**Comment by evanp** [comment]
All this said, I think it'd probably be good for us to add some warnings into the system. I'm going to start opening these as new issues; please comment there.

**Comment by evanp** [comment]
I added (and implemented and closed) #7, #8, and #10. There may be finer ones worth discussing.

**Comment by evanp** [comment]
I'm closing this in favour of more specific issues
